runtime: nodejs20
env: standard
service: brain_agriculture

network:
  instance_tag: brain_agriculture-service

automatic_scaling:
  min_instances: 1
  max_instances: 1

env_variables:
  DEBUG: false
  TZ: America/Sao_Paulo
  APP_ENV: PROD